"""add: new field dimension for embedding model

Revision ID: 68e680c2214c
Revises: 255321f70aef
Create Date: 2025-11-16 10:37:42.840619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68e680c2214c'
down_revision: Union[str, Sequence[str], None] = '255321f70aef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('dimension', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'dimension')
    # ### end Alembic commands ###
